// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrQle3K5XzOFWlz769nfko5H1B9l_tVoU',
    appId: '1:277345350920:web:c7b006270a620fcb0728bd',
    messagingSenderId: '277345350920',
    projectId: 'socialapp-3ce9b',
    authDomain: 'socialapp-3ce9b.firebaseapp.com',
    storageBucket: 'socialapp-3ce9b.firebasestorage.app',
    measurementId: 'G-HTB6J44FHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI1aYxBPfYrZeFqEITskHsGemGsEQFp5w',
    appId: '1:277345350920:android:87dd00b17ffea7b50728bd',
    messagingSenderId: '277345350920',
    projectId: 'socialapp-3ce9b',
    storageBucket: 'socialapp-3ce9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcCz3UZi5J33CucJUAZU2fywQ61sBSbTM',
    appId: '1:277345350920:ios:c6de4d8b9addb8870728bd',
    messagingSenderId: '277345350920',
    projectId: 'socialapp-3ce9b',
    storageBucket: 'socialapp-3ce9b.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcCz3UZi5J33CucJUAZU2fywQ61sBSbTM',
    appId: '1:277345350920:ios:c6de4d8b9addb8870728bd',
    messagingSenderId: '277345350920',
    projectId: 'socialapp-3ce9b',
    storageBucket: 'socialapp-3ce9b.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrQle3K5XzOFWlz769nfko5H1B9l_tVoU',
    appId: '1:277345350920:web:6d96476fc0d6b01e0728bd',
    messagingSenderId: '277345350920',
    projectId: 'socialapp-3ce9b',
    authDomain: 'socialapp-3ce9b.firebaseapp.com',
    storageBucket: 'socialapp-3ce9b.firebasestorage.app',
    measurementId: 'G-ZRM6JFLB8W',
  );
}
